services:
  web:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: battlefleet_server
    ports:
      - "8001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BATTLEFLEET_SECRET_KEY=dev_secret_key_here
    volumes:
      - ./instance:/app/backend/instance